/** Real-browser publication regression. All external app calls are intercepted;
 * fixtures never send email. Production behavior is evaluated separately. */
import {chromium,webkit} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..'),engine=process.env.BROWSER||'chromium',out=path.join(root,'test-results',engine,'publication');await fs.mkdir(out,{recursive:true});
const sources=['Aeon','Quanta Magazine','The Marginalian','Works in Progress'];
const items=Array.from({length:36},(_,i)=>({position:i,title:i===0?'What a forest knows about time':`An original perspective on ${['history','science','culture','cities'][i%4]} ${i+1}`,url:`https://example.com/original-${i}`,source:sources[i%4],origin:'subscribed fresh',minutes:6,section_name:['History','Science','Culture','Cities'][i%4],reason:`Placed ${i===0?'first as an accessible lead':'here as a contrasting perspective'} for its account of ${['history','science','culture','cities'][i%4]}.`}));
const edition={id:'30000000-0000-0000-0000-000000000001',kind:'daily',title:'Long Form',created_at:'2026-10-01T13:00:00Z',items,minutes:216,featured:[0,9,18,27,1],featured_minutes:30,introduction:'A welcoming science lead, a historical detour, and a change of perspective. Start here; the rest is yours to return to.',preparation:{status:'ready'},issues:[],editorial:{organization:{status:'edited'}}};
const reader={user:{id:'10000000-0000-0000-0000-000000000001',email:'reader@example.com'},settings:{onboarding_complete:true,kindle_email:'sample@kindle.com',paused:true,delivery_time:'06:00',timezone:'UTC',editorial_brief:'Original ideas, history and science.',editorial_instructions:''},sources:sources.map((name,i)=>({id:`f${i}`,name,url:`https://example.com/feed-${i}`,enabled:true})),sections:[],jobs:[],digests:[]};
const server=http.createServer(async(req,res)=>{const file={'/':'index.html','/styles.css':'styles.css','/publication.css':'publication.css','/publication.js':'publication.js','/opml.js':'opml.js','/starter-editions.js':'starter-editions.js'}[new URL(req.url,'http://local').pathname];if(!file){res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.css')?'text/css':file.endsWith('.js')?'application/javascript':'text/html');res.end(await fs.readFile(path.join(root,file)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;
const browser=await(engine==='webkit'?webkit:chromium).launch();const results=[],errors=[];
try{for(const width of (process.env.WIDTHS||'320,390,1440').split(',').map(Number)){
 const ctx=await browser.newContext({viewport:{width,height:844},isMobile:width<700,hasTouch:width<700,reducedMotion:'reduce'}),page=await ctx.newPage();let messages=[],states={},calls=[],jobCalls=0;
 page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.origin===base)return route.continue();if(!u.pathname.includes('/functions/v1/app-api'))return route.abort();const endpoint=u.pathname.split('/app-api')[1],body=route.request().postDataJSON();calls.push({endpoint,body});let data;
 if(endpoint==='/auth/verify-code')data={...reader,token:'synthetic-session'};
 else if(endpoint==='/auth/request-code')data={};else if((endpoint==='/state'||endpoint==='/me'))data=reader;
 else if(endpoint==='/publication/editions')data={editions:[edition]};
 else if(endpoint==='/reader/article'){const key=`${body.edition_id}:${body.position}`,a=items[body.position||0];data={article:{...a,body:Array.from({length:48},(_,i)=>`<p>Paragraph ${i+1}: The author argues that forests change through relationships across generations. A patient observation reveals patterns invisible to short-term measurement, and complicates our assumptions about progress.</p>`).join('')},paragraphs:Array.from({length:48},(_,i)=>`Paragraph ${i+1}: The author argues that forests change through relationships across generations. A patient observation reveals patterns invisible to short-term measurement, and complicates our assumptions about progress.`),article_key:key,reading:states[key]||{progress:0,paragraph:0,saved:false}};}
 else if(endpoint==='/reader/state'){const key=`${body.edition_id}:${body.position}`;states[key]={...states[key],...body,updated_at:new Date().toISOString()};data={ok:true};}
 else if(endpoint==='/editor/history')data={messages};
 else if(endpoint==='/editor/message'){const response=body.question==='Send this to my Kindle.'?{answer:'Review the exact complete edition. Nothing sent yet.',citations:[],send_request:{edition_id:body.edition_id}}:body.question.includes('less')?{answer:'I’ll use that direction in this conversation. Save it separately for future nighttime editions.',citations:[]}:body.question.includes('unavailable')?{answer:'The editor is temporarily unavailable. Your original reading remains available.',unavailable:true,citations:[]}:{answer:`The original ${items[0].title} leads this edition because its account of relationships across generations welcomes a slower reading pace. This is subscribed material. The visible paragraphs explain the author’s contrast with short-term measurement.`,citations:[{...items[0],edition_id:edition.id}]};const m={id:'message-'+messages.length,question:body.question,response,proposed_guidance:body.question.includes('less')?'Less work; more history, science and strange culture.':null};messages.push(m);data={message:m};}
 else if(endpoint==='/editor/confirm'){messages.find(m=>m.id===body.message_id).confirmed_at=new Date().toISOString();data={ok:true};}
 else if(endpoint==='/publication/feed')data={items,feeds:[]};else if(endpoint==='/reader/open')data={article_id:'40000000-0000-0000-0000-000000000001'};
 else if(endpoint==='/publication/send')data={job_id:'delivery-job',status:'queued'};
 else if(endpoint==='/publication/job')data={job:{status:++jobCalls===1?'running':'partial',result:{issues:['One publisher image could not be included.']}},edition_id:edition.id};
 else if(endpoint==='/reader/library')data={states:Object.entries(states).map(([article_key,s])=>({article_key,...s})),articles:[]};else throw new Error('Unexpected API '+endpoint);
 await route.fulfill({contentType:'application/json',body:JSON.stringify(data)});});
 async function capture(name){await page.screenshot({path:path.join(out,`${width}-${name}.png`),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);const violations=(await new AxeBuilder({page}).exclude('#original-reader').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));results.push({width,name,overflow,violations});assert.equal(overflow,false,`${name} horizontal overflow ${width}`);assert.deepEqual(violations,[],`${name} accessibility ${width}`);}
 await page.goto(base);await page.locator('#email').fill('reader@example.com');await page.locator('#login-submit').click();await page.locator('#code').fill('123456');await page.locator('#verify-form .primary').click();await page.locator('#prepare-publication').waitFor();await capture('today');
 assert.equal(await page.locator('.unread-count').count(),0);await page.locator('.today-edition .edition-link').click();await page.locator('.featured-reading .publication-item').first().waitFor();assert.equal(await page.locator('.featured-reading .publication-item').count(),5);assert.equal(await page.locator('.further-reading .publication-item').count(),31);await capture('edition');await page.locator('.further-reading summary').click();assert.equal(await page.locator('.publication-item:visible').count(),36);await page.locator('.further-reading summary').click();
 await page.locator('.featured-reading .publication-item').first().click();const frame=page.frameLocator('#original-reader');await frame.locator('p').first().waitFor();assert.equal(await page.getByRole('link',{name:'Next original →'}).getAttribute('href'),`#read/${edition.id}/9/featured`,'Reader follows finite featured sequence');await frame.locator('body').evaluate(e=>window.scrollTo(0,800));await page.waitForTimeout(500);await page.locator('#save-reading').click();await capture('reader');const position=await frame.locator('body').evaluate(()=>scrollY);assert.ok(position>500);
 await page.locator('#discuss-reading').click();await page.locator('#editor-question').fill('I don’t understand the author’s argument in these two paragraphs.');await page.locator('#ask-editor').click();await page.locator('.editor-exchange').waitFor();assert.ok(calls.find(c=>c.endpoint==='/editor/message').body.paragraph>0);await capture('discussion');await page.reload();await page.getByRole('link',{name:'Return to reading →'}).waitFor();assert.match(await page.locator('.reading-context').innerText(),/What a forest knows/,'Discussion keeps the actual article across reload');await page.getByRole('link',{name:'Return to reading →'}).click();await frame.locator('p').first().waitFor();await page.waitForTimeout(250);assert.ok(Math.abs(await frame.locator('body').evaluate(()=>scrollY)-position)<40,'reading position retained');
 await page.goBack();await page.locator('#editor-question').waitFor();await page.locator('#editor-question').fill('I want less AI and work at night and more history, science and strange culture.');await page.locator('#ask-editor').click();await page.locator('.confirm-guidance').waitFor();assert.equal(calls.filter(c=>c.endpoint==='/editor/confirm').length,0);await capture('steering');await page.locator('.confirm-guidance').click();assert.equal(calls.filter(c=>c.endpoint==='/editor/confirm').length,1);
 await page.locator('#editor-question').fill('unavailable');await page.locator('#ask-editor').click();await page.locator('.editor-answer.notice').waitFor();await capture('ai-unavailable');
 await page.getByRole('link',{name:'Explore',exact:true}).click();await page.locator('#raw-feed').click();await page.locator('.raw-feed-item').first().waitFor();assert.equal(await page.locator('.raw-feed-item').count(),36);await capture('raw-feed');await page.locator('.raw-feed-item').first().click();await frame.locator('p').first().waitFor();
 await page.goto(base+'/#edition/'+edition.id);await page.locator('#send-edition').waitFor();await page.getByRole('link',{name:'Editor',exact:true}).click();await page.locator('#editor-question').fill('Send this to my Kindle.');await page.locator('#ask-editor').click();await page.locator('#confirm-edition-send').waitFor();assert.equal(calls.filter(c=>c.endpoint==='/publication/send').length,0,'Discussion opens review before any send');assert.equal(calls.filter(c=>c.endpoint==='/editor/message').at(-1).body.edition_id,edition.id);await capture('exact-send');await page.locator('#close-modal').click();await page.locator('#editor-question').fill('Why this edition?');await page.locator('#ask-editor').click();await page.locator('.editor-exchange').last().getByText(/The original/).waitFor();await page.locator('.review-send-request').click();await page.locator('#confirm-edition-send').waitFor();await page.locator('#confirm-edition-send').click();await page.getByText('Submitted with notes.',{exact:true}).waitFor();await capture('delivery-status');assert.match(await page.locator('#delivery-status').innerText(),/Arrival|arrival/);assert.match(await page.locator('#delivery-issues').innerText(),/publisher image/);await page.reload();await page.getByText('Submitted with notes.',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Library',exact:true}).click();await page.locator('.library-saved').waitFor();await capture('library');assert.ok(states[`${edition.id}:0`].saved);await ctx.close();
 }}finally{await browser.close();server.close();await fs.writeFile(path.join(out,'results.json'),JSON.stringify({results,errors},null,2));}assert.deepEqual(errors,[]);console.log(`${engine}: ${results.length} publication screenshots; no overflow, accessibility or script errors.`);
