/** Isolated replay regression. No real credentials, account data, or outgoing requests. */
import {chromium} from 'playwright';import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve(import.meta.dirname,'..');const article={title:'A patient original',source:'Test source',minutes:3,origin:'subscribed fresh',url:'https://example.com/original'};
const edition={id:'test-edition',kind:'tonight',title:'Tonight’s Reading',created_at:'2026-10-01T13:00:00Z',items:[article],minutes:3,featured:[0],featured_minutes:3,preparation:{status:'ready'}};
const snapshot={version:1,responses:{'/me':{user:{id:'validation',email:'validation@resend.dev'},settings:{onboarding_complete:true,paused:true,timezone:'UTC',kindle_email:'test@kindle.com'},sources:[],sections:[],jobs:[],digests:[]},'/publication/editions':{editions:[edition]},'/reader/library':{states:[],articles:[]},'/editor/history':{messages:[]}},articles:{'test-edition:0':{article:{...article,body:Array.from({length:30},(_,i)=>`<p>Paragraph ${i+1}: A complete <em>original</em>, in an isolated replay. Reading takes patience, observation and time. Its account includes the original author’s reasoning, and stays available for later discussion.</p>`).join('')},article_key:'test-edition:0',paragraphs:Array.from({length:30},(_,i)=>`Paragraph ${i+1}: A complete original , in an isolated replay. Reading takes patience, observation and time. Its account includes the original author’s reasoning, and stays available for later discussion.`),reading:{saved:false,progress:0,paragraph:0}}}};
const files={'/':'index.html','/developer':'developer.html','/developer.js':'developer.js','/publication.js':'publication.js','/publication.css':'publication.css','/styles.css':'styles.css','/opml.js':'opml.js','/starter-editions.js':'starter-editions.js'};
let apiRequests=0;const server=http.createServer(async(req,res)=>{const file=files[new URL(req.url,'http://test').pathname];if(!file){apiRequests++;res.writeHead(404);return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await fs.readFile(path.join(root,file)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch();const page=await browser.newPage();const errors=[],outgoing=[];page.on('pageerror',e=>errors.push(e.message));const base=`http://127.0.0.1:${server.address().port}`;
await page.route('**/*',route=>{if(new URL(route.request().url()).origin===base)return route.continue();outgoing.push(route.request().url());return route.abort();});
try{
 await page.goto(base+'/developer');await page.evaluate(()=>localStorage.setItem('longFormToken','existing-parent-session'));
 await page.getByText('Paste snapshot instead',{exact:true}).click();await page.getByLabel('Snapshot JSON',{exact:true}).fill(JSON.stringify(snapshot));await page.getByRole('button',{name:'Load snapshot',exact:true}).click();const app=page.frameLocator('#qa-frame');await app.getByRole('link',{name:'Start reading',exact:true}).click();await app.frameLocator('#original-reader').locator('p').first().waitFor();await app.getByRole('button',{name:'Save',exact:true}).click();await app.getByRole('button',{name:'Saved',exact:true}).waitFor();await app.locator('#original-reader').evaluate(el=>{const p=el.contentDocument.querySelectorAll('p')[12];el.ownerDocument.defaultView.scrollTo(0,el.getBoundingClientRect().top+el.ownerDocument.defaultView.scrollY+p.offsetTop-80)});await app.getByRole('button',{name:'Discuss',exact:true}).click();await app.locator('.reading-passage summary').click();assert.match(await app.locator('.reading-passage blockquote').innerText(),/^Paragraph 13:/,'Nested replay retains the actual visible paragraph');await app.getByRole('link',{name:'Library',exact:true}).click();await app.locator('.library-saved').waitFor();assert.equal(await app.locator('.library-saved').innerText(),article.title);
 assert.equal(await page.evaluate(()=>localStorage.getItem('longFormToken')),'existing-parent-session');assert.equal(await page.evaluate(()=>Object.keys(sessionStorage).length),0);
 await app.locator('.edition-link').click();await app.getByRole('button',{name:'Send this edition to Kindle',exact:true}).click();await app.getByRole('button',{name:'Send this edition',exact:true}).click();await app.getByText(/No request was sent/).waitFor();
 await page.getByRole('button',{name:'Reset replay',exact:true}).click();await app.getByRole('link',{name:'Start reading',exact:true}).click();await app.getByRole('button',{name:'Save',exact:true}).waitFor();assert.equal(await app.getByRole('button',{name:'Saved',exact:true}).count(),0);
 await page.locator('#qa-scenario').selectOption('empty');await app.getByRole('heading',{name:'Your first edition.',exact:true}).waitFor();await page.locator('#qa-scenario').selectOption('error');await app.getByRole('heading',{name:'Couldn’t open this page.',exact:true}).waitFor();
 assert.deepEqual(errors,[]);assert.deepEqual(outgoing,[]);assert.equal(apiRequests,0);console.log('PASS: replay storage isolated, reading saved locally, reset clears state, sends and all outgoing API calls blocked; empty/error scenarios render.');
}finally{await browser.close();server.close();}
