import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';
const db=new PGlite(),user='10000000-0000-0000-0000-000000000001',other='10000000-0000-0000-0000-000000000002',job='20000000-0000-0000-0000-000000000001',edition='30000000-0000-0000-0000-000000000001',message='40000000-0000-0000-0000-000000000001';
const file=fs.readdirSync(new URL('../supabase/migrations',import.meta.url)).find(f=>f.endsWith('_personal_publication.sql'));
const ready=(async()=>{await db.exec(`create role anon;create role authenticated;create role service_role;
create table app_users(id uuid primary key);create table user_settings(user_id uuid primary key,kindle_email text,timezone text default 'UTC',delivery_time time default '06:00',paused boolean default true,onboarding_complete boolean default true);
create table feeds(id uuid primary key,user_id uuid,enabled boolean default true,archived_at timestamptz);
create table digest_jobs(id uuid primary key default gen_random_uuid(),user_id uuid references app_users(id),reason text constraint digest_jobs_reason_check check(reason in ('manual','scheduled','test','one_time','first_run_preview')),status text default 'queued',error text,finished_at timestamptz,lookback_hours int default 48,idempotency_key text unique,run_after timestamptz default now(),result jsonb default '{}',created_at timestamptz default now());
create table delivery_outbox(job_id uuid primary key references digest_jobs(id),payload jsonb,first_send_at timestamptz,provider_email_id text);
`);await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));const summaries=fs.readdirSync(new URL('../supabase/migrations',import.meta.url)).find(f=>f.endsWith('_publication_summaries.sql'));await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+summaries,import.meta.url),'utf8'));await db.exec(fs.readFileSync(new URL('../supabase/migrations/20261001053800_delivery_payload_freeze.sql',import.meta.url),'utf8'));await db.exec(fs.readFileSync(new URL('../supabase/migrations/20261001062200_publication_preparation_writes.sql',import.meta.url),'utf8'));})();
async function isolated(work){await ready;await db.exec('begin');try{await db.query('insert into app_users values($1),($2)',[user,other]);await db.query('insert into user_settings(user_id,kindle_email) values($1,$2)',[user,'reader@kindle.com']);await db.query("insert into digest_jobs(id,user_id,reason,status) values($1,$2,'publication_preview','ready')",[job,user]);await db.query('insert into publication_editions(id,user_id,job_id,kind,title,manifest) values($1,$2,$3,$4,$5,$6)',[edition,user,job,'tonight','Tonight’s Reading',JSON.stringify({items:[{title:'Original A'},{title:'Original B'}]})]);await db.query('insert into delivery_outbox(job_id,payload) values($1,$2)',[job,JSON.stringify({email:{to:[],subject:'Frozen subject',attachments:[{content:'exact-reviewed-bytes'}]},groups:[{items:[{title:'Original A'},{title:'Original B'}]}]})]);await work();}finally{await db.exec('rollback');}}
async function rejected(work,pattern){await db.exec('savepoint expected_failure');try{await assert.rejects(work,pattern);}finally{await db.exec('rollback to expected_failure');}}
const queue=(u=user,k='same-request')=>db.query('select queue_publication_delivery($1,$2,$3) as id',[u,edition,k]);
test.after(async()=>{await ready;await db.close()});
test('exact edition delivery retries return the same job, order and attachment bytes',()=>isolated(async()=>{const first=(await queue()).rows[0].id,second=(await queue()).rows[0].id;assert.equal(first,second);const payload=(await db.query('select payload from delivery_outbox where job_id=$1',[first])).rows[0].payload;assert.equal(payload.email.attachments[0].content,'exact-reviewed-bytes');assert.deepEqual(payload.groups[0].items.map(i=>i.title),['Original A','Original B']);assert.deepEqual(payload.email.to,['reader@kindle.com']);}));
test('wrong tenant and expired frozen editions fail closed',()=>isolated(async()=>{await rejected(()=>queue(other),/not found/);await db.query('update delivery_outbox set payload=null where job_id=$1',[job]);await rejected(()=>queue(),/expired/);assert.equal((await db.query('select count(*) from digest_jobs')).rows[0].count,1);}));
test('durable nighttime guidance requires a separate tenant-bound confirmation and detects concurrent changes',()=>isolated(async()=>{await db.query('insert into editor_messages(id,user_id,request_key,question,response,proposed_guidance) values($1,$2,$3,$4,$5,$6)',[message,user,'proposal-request','Less work at night',JSON.stringify({base_guidance:''}),'History, science and strange culture.']);assert.equal((await db.query('select evening_editorial_instructions from user_settings')).rows[0].evening_editorial_instructions,'');await rejected(()=>db.query('select confirm_editor_guidance($1,$2)',[other,message]),/not found/);await db.query('update user_settings set evening_editorial_instructions=$1',['A competing change']);await rejected(()=>db.query('select confirm_editor_guidance($1,$2)',[user,message]),/changed/);await db.query("update user_settings set evening_editorial_instructions=''");await db.query('select confirm_editor_guidance($1,$2)',[user,message]);await db.query('select confirm_editor_guidance($1,$2)',[user,message]);assert.equal((await db.query('select evening_editorial_instructions from user_settings')).rows[0].evening_editorial_instructions,'History, science and strange culture.');}));
test('all publication tables deny direct client access and have RLS',async()=>{await ready;const rows=(await db.query("select c.relname,c.relrowsecurity,has_table_privilege('anon',c.oid,'select') as anon,has_table_privilege('authenticated',c.oid,'select') as authenticated from pg_class c where c.relname in ('publication_editions','reader_articles','reading_states','editor_messages','editor_conversations')")).rows;assert.equal(rows.length,5);assert.ok(rows.every(r=>r.relrowsecurity&&!r.anon&&!r.authenticated));});
test('proactive web editions are scheduled while Kindle is paused, once per local date',()=>isolated(async()=>{await db.query('delete from publication_editions');await db.query('delete from delivery_outbox');await db.query('delete from digest_jobs');await db.query('insert into feeds(id,user_id) values($1,$2)',[job,user]);await db.query("select queue_due_web_publications('2026-10-01T07:00:00Z')");await db.query("select queue_due_web_publications('2026-10-01T07:05:00Z')");assert.equal((await db.query('select count(*) from digest_jobs')).rows[0].count,1);assert.equal((await db.query('select reason from digest_jobs')).rows[0].reason,'publication_preview');}));

test('reading progress and saved flags survive independent partial updates',()=>isolated(async()=>{await db.query('select update_reading_state($1,$2,null,null,true)',[user,'article']);await db.query('select update_reading_state($1,$2,0.42,7,null)',[user,'article']);await db.query('select update_reading_state($1,$2,null,null,false)',[user,'article']);const row=(await db.query('select * from reading_states')).rows[0];assert.equal(row.saved,false);assert.equal(row.paragraph,7);assert.ok(Math.abs(row.progress-0.42)<0.001);}));

test('observable job status excludes frozen bodies and respects tenant isolation',()=>isolated(async()=>{await db.query('update digest_jobs set result=$1 where id=$2',[JSON.stringify({preparation_manifest:{body:'private original bytes'},articles:3,issues:['One media omission']}),job]);const status=(await db.query('select publication_job_status($1,$2) as status',[user,job])).rows[0].status;assert.equal(status.job.result.articles,3);assert.ok(!JSON.stringify(status).includes('private original bytes'));assert.equal((await db.query('select publication_job_status($1,$2) as status',[other,job])).rows[0].status,null);}));

test('bounded backend payload freeze verifies tenant, preserves exact bytes and cannot replace a frozen artifact',()=>isolated(async()=>{
 const payload=(await db.query('select payload from delivery_outbox where job_id=$1',[job])).rows[0].payload;
 await rejected(()=>db.query('select freeze_delivery_payload($1,$2,$3)',[job,other,JSON.stringify(payload)]),/not found/);
 await rejected(()=>db.query('select freeze_delivery_payload($1,$2,$3)',[job,user,JSON.stringify({...payload,groups:[]})]),/cannot be replaced/);
 await db.query("update delivery_outbox set provider_email_id='accepted' where job_id=$1",[job]);
 const result=(await db.query('select freeze_delivery_payload($1,$2,$3) as metadata',[job,user,JSON.stringify(payload)])).rows[0].metadata;
 assert.equal(result.provider_email_id,'accepted');assert.ok(!JSON.stringify(result).includes('exact-reviewed-bytes'));
 const config=(await db.query("select proconfig,has_function_privilege('anon',oid,'execute') as anon from pg_proc where proname='freeze_delivery_payload'")).rows[0];
 assert.ok(config.proconfig.includes('statement_timeout=30s'));assert.equal(config.anon,false);
}));

test('media checkpoints and publication archives use tenant-checked bounded writes and preserve frozen editions',()=>isolated(async()=>{
 await rejected(()=>db.query('select checkpoint_digest_preparation($1,$2,$3)',[job,other,'{}']),/not found/);
 await db.query('update digest_jobs set result=$1 where id=$2',[JSON.stringify({publication_kind:'tonight'}),job]);
 await db.query('select checkpoint_digest_preparation($1,$2,$3)',[job,user,JSON.stringify({version:3,groups:[]})]);
 const result=(await db.query('select result from digest_jobs where id=$1',[job])).rows[0].result;assert.equal(result.publication_kind,'tonight');assert.equal(result.preparation_manifest.version,3);
 await rejected(()=>db.query('select archive_publication_edition($1,$2,$3,$4,$5,$6,$7)',[job,other,'tonight','Other',35,'{}','{}']),/not found/);
 const id=(await db.query('select archive_publication_edition($1,$2,$3,$4,$5,$6,$7) as id',[job,user,'tonight','Replacement',35,'{}','{}'])).rows[0].id;assert.equal(id,edition);
 assert.equal((await db.query('select title from publication_editions where id=$1',[edition])).rows[0].title,'Tonight’s Reading');
 const functions=(await db.query("select proconfig,has_function_privilege('anon',oid,'execute') as anon from pg_proc where proname in ('checkpoint_digest_preparation','archive_publication_edition')")).rows;assert.equal(functions.length,2);assert.ok(functions.every(f=>f.proconfig.includes('statement_timeout=30s')&&!f.anon));
}));
